# Generated by Django 3.0.5 on 2020-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'administrator'), (3, 'moderator')], default=1),
        ),
    ]
