# Generated by Django 3.0.5 on 2020-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
