# Generated by Django 3.0.5 on 2020-11-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
