# Generated by Django 3.0.5 on 2020-11-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_comment', to='api.Reviews'),
            preserve_default=False,
        ),
    ]
